version: "3.7"
services:
  jetstream:
    image: synadia/jsm:nightly
    command: ["server", "--debug"]
    expose:
      - "4222"
    network_mode: "host"
  consumer:
    image: eventserver/consumer
    working_dir: /app
    build:
      context: ./consumer
    restart: always
    volumes:
      - ./consumer/:/app
    network_mode: "host"
  producer:
    image: eventserver/producer
    working_dir: /app
    build:
      context: ./producer
    restart: always
    command: npm start
    volumes:
      - type: bind
        source: ./producer
        target: /app
    expose:
      - "3000"
    network_mode: "host"
volumes:
  driver: {}
